export interface SurahTranslation {
  number: number;
  transliteration: string;
  translation: string;
}

export const surahTranslations: Record<number, SurahTranslation> = {
  1: { number: 1, transliteration: "Al-Fatihah", translation: "The Opening" },
  2: { number: 2, transliteration: "Al-Baqarah", translation: "The Cow" },
  3: { number: 3, transliteration: "Aal-Imran", translation: "The Family of Imran" },
  4: { number: 4, transliteration: "An-Nisa", translation: "The Women" },
  5: { number: 5, transliteration: "Al-Ma'idah", translation: "The Table Spread" },
  6: { number: 6, transliteration: "Al-An'am", translation: "The Cattle" },
  7: { number: 7, transliteration: "Al-A'raf", translation: "The Heights" },
  8: { number: 8, transliteration: "Al-Anfal", translation: "The Spoils of War" },
  9: { number: 9, transliteration: "At-Tawbah", translation: "The Repentance" },
  10: { number: 10, transliteration: "Yunus", translation: "Jonah" },
  11: { number: 11, transliteration: "Hud", translation: "Hud" },
  12: { number: 12, transliteration: "Yusuf", translation: "Joseph" },
  13: { number: 13, transliteration: "Ar-Ra'd", translation: "The Thunder" },
  14: { number: 14, transliteration: "Ibrahim", translation: "Abraham" },
  15: { number: 15, transliteration: "Al-Hijr", translation: "The Rocky Tract" },
  16: { number: 16, transliteration: "An-Nahl", translation: "The Bee" },
  17: { number: 17, transliteration: "Al-Isra", translation: "The Night Journey" },
  18: { number: 18, transliteration: "Al-Kahf", translation: "The Cave" },
  19: { number: 19, transliteration: "Maryam", translation: "Mary" },
  20: { number: 20, transliteration: "Ta-Ha", translation: "Ta-Ha" },
  21: { number: 21, transliteration: "Al-Anbiya", translation: "The Prophets" },
  22: { number: 22, transliteration: "Al-Hajj", translation: "The Pilgrimage" },
  23: { number: 23, transliteration: "Al-Mu'minun", translation: "The Believers" },
  24: { number: 24, transliteration: "An-Nur", translation: "The Light" },
  25: { number: 25, transliteration: "Al-Furqan", translation: "The Criterion" },
  26: { number: 26, transliteration: "Ash-Shu'ara", translation: "The Poets" },
  27: { number: 27, transliteration: "An-Naml", translation: "The Ant" },
  28: { number: 28, transliteration: "Al-Qasas", translation: "The Narration" },
  29: { number: 29, transliteration: "Al-'Ankabut", translation: "The Spider" },
  30: { number: 30, transliteration: "Ar-Rum", translation: "The Romans" },
  31: { number: 31, transliteration: "Luqman", translation: "Luqman" },
  32: { number: 32, transliteration: "As-Sajdah", translation: "The Prostration" },
  33: { number: 33, transliteration: "Al-Ahzab", translation: "The Combined Forces" },
  34: { number: 34, transliteration: "Saba", translation: "Sheba" },
  35: { number: 35, transliteration: "Fatir", translation: "The Originator" },
  36: { number: 36, transliteration: "Ya-Sin", translation: "Ya-Sin" },
  37: { number: 37, transliteration: "As-Saffat", translation: "Those Who Set The Ranks" },
  38: { number: 38, transliteration: "Sad", translation: "Sad" },
  39: { number: 39, transliteration: "Az-Zumar", translation: "The Groups" },
  40: { number: 40, transliteration: "Ghafir", translation: "The Forgiver" },
  41: { number: 41, transliteration: "Fussilat", translation: "Explained in Detail" },
  42: { number: 42, transliteration: "Ash-Shura", translation: "The Consultation" },
  43: { number: 43, transliteration: "Az-Zukhruf", translation: "The Gold Adornment" },
  44: { number: 44, transliteration: "Ad-Dukhan", translation: "The Smoke" },
  45: { number: 45, transliteration: "Al-Jathiyah", translation: "The Kneeling" },
  46: { number: 46, transliteration: "Al-Ahqaf", translation: "The Wind-Curved Sandhills" },
  47: { number: 47, transliteration: "Muhammad", translation: "Muhammad" },
  48: { number: 48, transliteration: "Al-Fath", translation: "The Victory" },
  49: { number: 49, transliteration: "Al-Hujurat", translation: "The Private Chambers" },
  50: { number: 50, transliteration: "Qaf", translation: "Qaf" },
  51: { number: 51, transliteration: "Adh-Dhariyat", translation: "The Winnowing Winds" },
  52: { number: 52, transliteration: "At-Tur", "translation": "The Mount" },
  53: { number: 53, transliteration: "An-Najm", translation: "The Star" },
  54: { number: 54, transliteration: "Al-Qamar", translation: "The Moon" },
  55: { number: 55, transliteration: "Ar-Rahman", translation: "The Beneficent" },
  56: { number: 56, transliteration: "Al-Waqi'ah", translation: "The Inevitable" },
  57: { number: 57, transliteration: "Al-Hadid", translation: "The Iron" },
  58: { number: 58, transliteration: "Al-Mujadila", translation: "The Pleading Woman" },
  59: { number: 59, transliteration: "Al-Hashr", translation: "The Exile" },
  60: { number: 60, transliteration: "Al-Mumtahanah", translation: "She That Is To Be Examined" },
  61: { number: 61, transliteration: "As-Saff", translation: "The Ranks" },
  62: { number: 62, transliteration: "Al-Jumu'ah", translation: "The Friday" },
  63: { number: 63, transliteration: "Al-Munafiqun", translation: "The Hypocrites" },
  64: { number: 64, transliteration: "At-Taghabun", translation: "The Mutual Loss and Gain" },
  65: { number: 65, transliteration: "At-Talaq", translation: "The Divorce" },
  66: { number: 66, transliteration: "At-Tahrim", translation: "The Prohibition" },
  67: { number: 67, transliteration: "Al-Mulk", translation: "The Sovereignty" },
  68: { number: 68, transliteration: "Al-Qalam", translation: "The Pen" },
  69: { number: 69, transliteration: "Al-Haqqah", translation: "The Reality" },
  70: { number: 70, transliteration: "Al-Ma'arij", translation: "The Ascending Stairways" },
  71: { number: 71, transliteration: "Nuh", translation: "Noah" },
  72: { number: 72, transliteration: "Al-Jinn", translation: "The Jinn" },
  73: { number: 73, transliteration: "Al-Muzzammil", translation: "The Enshrouded One" },
  74: { number: 74, transliteration: "Al-Muddaththir", translation: "The Cloaked One" },
  75: { number: 75, transliteration: "Al-Qiyamah", translation: "The Resurrection" },
  76: { number: 76, transliteration: "Al-Insan", translation: "The Man" },
  77: { number: 77, transliteration: "Al-Mursalat", translation: "The Emissaries" },
  78: { number: 78, transliteration: "An-Naba", translation: "The Announcement" },
  79: { number: 79, transliteration: "An-Nazi'at", translation: "Those Who Pull Out" },
  80: { number: 80, transliteration: "Abasa", translation: "He Frowned" },
  81: { number: 81, transliteration: "At-Takwir", translation: "The Overthrowing" },
  82: { number: 82, transliteration: "Al-Infitar", translation: "The Cleaving" },
  83: { number: 83, transliteration: "Al-Mutaffifin", translation: "The Defrauding" },
  84: { number: 84, transliteration: "Al-Inshiqaq", translation: "The Splitting Asunder" },
  85: { number: 85, transliteration: "Al-Buruj", translation: "The Mansions of the Stars" },
  86: { number: 86, transliteration: "At-Tariq", translation: "The Morning Star" },
  87: { number: 87, transliteration: "Al-A'la", translation: "The Most High" },
  88: { number: 88, transliteration: "Al-Ghashiyah", translation: "The Overwhelming" },
  89: { number: 89, transliteration: "Al-Fajr", translation: "The Dawn" },
  90: { number: 90, transliteration: "Al-Balad", translation: "The City" },
  91: { number: 91, transliteration: "Ash-Shams", translation: "The Sun" },
  92: { number: 92, transliteration: "Al-Layl", translation: "The Night" },
  93: { number: 93, transliteration: "Ad-Duha", translation: "The Morning Hours" },
  94: { number: 94, transliteration: "Ash-Sharh", translation: "The Consolation" },
  95: { number: 95, transliteration: "At-Tin", translation: "The Fig" },
  96: { number: 96, transliteration: "Al-'Alaq", translation: "The Clot" },
  97: { number: 97, transliteration: "Al-Qadr", translation: "The Power" },
  98: { number: 98, transliteration: "Al-Bayyinah", translation: "The Clear Proof" },
  99: { number: 99, transliteration: "Az-Zalzalah", translation: "The Earthquake" },
  100: { number: 100, transliteration: "Al-'Adiyat", translation: "The Courser" },
  101: { number: 101, transliteration: "Al-Qari'ah", translation: "The Calamity" },
  102: { number: 102, transliteration: "At-Takathur", translation: "The Rivalry in World Increase" },
  103: { number: 103, transliteration: "Al-'Asr", translation: "The Declining Day" },
  104: { number: 104, transliteration: "Al-Humazah", translation: "The Traducer" },
  105: { number: 105, transliteration: "Al-Fil", translation: "The Elephant" },
  106: { number: 106, transliteration: "Quraysh", translation: "Quraysh" },
  107: { number: 107, transliteration: "Al-Ma'un", translation: "The Kindness" },
  108: { number: 108, transliteration: "Al-Kawthar", translation: "The Abundance" },
  109: { number: 109, transliteration: "Al-Kafirun", translation: "The Disbelievers" },
  110: { number: 110, transliteration: "An-Nasr", translation: "The Help" },
  111: { number: 111, transliteration: "Al-Masad", translation: "The Palm Fiber" },
  112: { number: 112, transliteration: "Al-Ikhlas", translation: "The Sincerity" },
  113: { number: 113, transliteration: "Al-Falaq", translation: "The Daybreak" },
  114: { number: 114, transliteration: "An-Nas", translation: "Mankind" }
};
